# Generated by Django 5.0.6 on 2024-05-28 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_votingbooth_municipality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('number_phone', models.IntegerField()),
                ('number_identification', models.IntegerField(unique=True)),
                ('coordinates', models.CharField(max_length=50, null=True)),
                ('user_id_created', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='voters_account', to=settings.AUTH_USER_MODEL)),
                ('votingbooth_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vootingbooth_id', to='locations.votingbooth')),
            ],
        ),
    ]
