# Generated by Django 5.0.6 on 2024-05-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingbooth',
            name='coordinates',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
