# Generated by Django 5.0.6 on 2024-05-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_votingbooth_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingbooth',
            name='municipality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.municipality'),
        ),
    ]
